import type { NextPage } from "next";
import Head from "next/head";

import { CalculatorPage } from "../src/components/pages";

const Home: NextPage = () => {
  return (
    <div className="max-w-5xl mx-auto">
      <Head>
        <title>Splitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CalculatorPage />
    </div>
  );
};

export default Home;
